# User constraints
USER_PASSWORD_MINIMUM_LENGTH = 4
USER_PASSWORD_MAXIMUM_LENGTH = 120
USER_USERNAME_MAXIMUM_LENGTH = 80
USER_NAME_MAXIMUM_LENGTH = 120
USER_EMAIL_MAXIMUM_LENGTH = 120

# Job constraints
JOB_TITLE_MAXIMUM_LENGTH = 100
JOB_COMPANY_NAME_MAXIMUM_LENGTH = 100
JOB_RECRUITER_NAME_MAXIMUM_LENGTH = USER_NAME_MAXIMUM_LENGTH
JOB_DESCRIPTION_MAXIMUM_LENGTH = 1000
